import {
  Building2,
  Landmark,
  ShieldAlert,
  ClipboardList,
  Sparkles,
  Key,
  Clock,
  Ticket,
  Cigarette,
  FileQuestion,
  IdCard,
  BookOpen,
  HeartPulse,
  ShieldPlus,
  FileSignature,
  Stamp,
  PlaneTakeoff,
  PlaneLanding,
  Car,
  type LucideIcon,
} from "lucide-react";

export const COMPANY_DOCUMENT_CATEGORY_ICONS: Record<string, LucideIcon> = {
  COMMERCIAL_REGISTRATION: Building2,
  MUNICIPAL_LICENSE: Landmark,
  CIVIL_DEFENSE_LICENSE: ShieldAlert,
  CIVIL_DEFENSE_REPORT: ClipboardList,
  CLEANING_CONTRACT: Sparkles,
  LEASE_CONTRACT: Key,
  TWENTY_FOUR_HOUR_PERMIT: Clock,
  ENTERTAINMENT_AUTHORITY_PERMIT: Ticket,
  TOBACCO_LICENSE: Cigarette,
  OTHER: FileQuestion,
};

export const EMPLOYEE_DOCUMENT_TYPE_ICONS: Record<string, LucideIcon> = {
  IQAMA: IdCard,
  PASSPORT: BookOpen,
  HEALTH_CERTIFICATE: HeartPulse,
  MEDICAL_INSURANCE: ShieldPlus,
  EMPLOYMENT_CONTRACT: FileSignature,
  VISA: Stamp,
  EXIT_REENTRY_VISA: PlaneTakeoff,
  FINAL_EXIT_VISA: PlaneLanding,
  FLIGHT_TICKET: Ticket,
  DRIVING_LICENSE: Car,
  OTHER: FileQuestion,
};
