import { Router } from "express";
import { z } from "zod";
import { requireAuth } from "@/middleware/auth";
import { validate } from "@/middleware/validate";
import { asyncHandler } from "@/utils/asyncHandler";
import { prisma } from "@/lib/prisma";
import { requireAccess } from "@/modules/productivity/productivity.service";
import { canViewSource, escapeHtml } from "@/lib/security";
import { getTrackableItems } from "@/services/expiringItems";
import { getBrandingContext } from "@/services/branding";
import { renderHtmlToPdf } from "@/services/pdf";
import { tableReportPdf } from "@/modules/pdf/templates";
import { pdfContentDisposition } from "@/utils/pdfHeaders";
import { L } from "@/services/lang";
import { ApiError } from "@/utils/apiError";
import * as schema from "./operations.schemas";
import * as service from "./operations.service";
import { financeOverview, financeQuery } from "./finance.service";
import * as requirements from "./requirements.service";
const router = Router(); router.use(requireAuth);
const params = z.object({ id: schema.id });
router.get("/finance", validate({ query: financeQuery }), asyncHandler(async (req, res) => { res.json({ data: await financeOverview(req.auth!, req.query as never) }); }));
router.get("/requirements", asyncHandler(async (req, res) => { res.json({ data: await requirements.listRequirements(req.auth!) }); }));
router.post("/requirements", validate({ body: requirements.requirementInput }), asyncHandler(async (req, res) => { res.status(201).json({ data: await requirements.saveRequirement(req.auth!, req.body) }); }));
router.put("/requirements/:id", validate({ params, body: requirements.requirementInput }), asyncHandler(async (req, res) => { res.json({ data: await requirements.saveRequirement(req.auth!, req.body, req.params.id as string) }); }));
router.get("/requirements/:id/missing", validate({ params, query: schema.list }), asyncHandler(async (req, res) => { res.json({ data: await requirements.missingDocuments(req.auth!, req.params.id as string, Number(req.query.page)) }); }));
router.post("/requirements/followup", validate({ body: requirements.followupInput }), asyncHandler(async (req, res) => { res.status(201).json({ data: await requirements.createMissingFollowup(req.auth!, req.body) }); }));
router.get("/assets", validate({ query: schema.list }), asyncHandler(async (req, res) => { res.json({ data: await service.listAssets(req.auth!, req.query as never) }); }));
router.post("/assets", validate({ body: schema.asset }), asyncHandler(async (req, res) => { res.status(201).json({ data: await service.createAsset(req.auth!, req.body) }); }));
router.post("/assets/:id/assign", validate({ params, body: schema.assign }), asyncHandler(async (req, res) => { res.json({ data: await service.assignAsset(req.auth!, req.params.id as string, req.body) }); }));
router.put("/assets/:id/state", validate({ params, body: schema.assetState }), asyncHandler(async (req, res) => { await service.setAssetState(req.auth!, req.params.id as string, req.body.state); res.json({ message: "Saved." }); }));
router.get("/assets/:id/history", validate({ params }), asyncHandler(async (req, res) => { res.json({ data: await service.assetHistory(req.auth!, req.params.id as string) }); }));
router.post("/handovers/:id/return", validate({ params, body: schema.returned }), asyncHandler(async (req, res) => { res.json({ data: await service.returnAsset(req.auth!, req.params.id as string, req.body) }); }));
router.get("/handovers/:id/pdf", validate({ params }), asyncHandler(async (req, res) => {
  requireAccess(req.auth!, "employees.view"); requireAccess(req.auth!, "employees.export");
  const row = await prisma.assetHandover.findUnique({ where: { id: req.params.id as string }, include: { asset: true, employee: { select: { fullNameAr: true, fullNameEn: true, employeeNumber: true } }, recordedBy: { select: { fullName: true } } } });
  if (!row) throw ApiError.notFound("Handover not found.");
  const facts = [[L("رقم المحضر", "Receipt reference"), row.id], [L("العهدة", "Asset"), `${row.asset.code} — ${row.asset.name}`], [L("الرقم التسلسلي", "Serial number"), row.asset.serialNumber], [L("الموظف", "Employee"), `${L(row.employee.fullNameAr, row.employee.fullNameEn || row.employee.fullNameAr)} — ${row.employee.employeeNumber}`], [L("تاريخ التسليم", "Issued at"), row.issuedAt.toISOString().slice(0, 10)], [L("حالة التسليم", "Issue condition"), row.issuedCondition], [L("تاريخ الإرجاع", "Returned at"), row.returnedAt?.toISOString().slice(0, 10)], [L("حالة الإرجاع", "Return condition"), row.returnedCondition], [L("المسجل", "Recorded by"), row.recordedBy.fullName], [L("ملاحظات", "Notes"), row.notes]].map(([label, value]) => ({ label, value }));
  const html = tableReportPdf("محضر تسليم واستلام عهدة", [{ header: "البيان", subHeader: "Field", render: r => escapeHtml(r.label) }, { header: "التفاصيل", subHeader: "Details", render: r => escapeHtml(r.value || "—") }], facts, await getBrandingContext(), { titleEn: "Asset Handover & Return Receipt" });
  const bytes = await renderHtmlToPdf(html, { footerLabel: L("محضر عهدة", "Asset receipt") });
  await prisma.auditLog.create({ data: { userId: req.auth!.userId, action: "EXPORT", module: "assets", recordId: row.id, description: "Printed asset handover receipt" } });
  res.setHeader("Content-Type", "application/pdf"); res.setHeader("Content-Disposition", pdfContentDisposition(`asset-${row.asset.code}.pdf`)); res.send(bytes);
}));
router.get("/offboarding", validate({ query: schema.list }), asyncHandler(async (req, res) => { res.json({ data: await service.listOffboarding(req.auth!, req.query as never) }); }));
router.post("/offboarding", validate({ body: schema.offboarding }), asyncHandler(async (req, res) => { res.status(201).json({ data: await service.startOffboarding(req.auth!, req.body) }); }));
router.put("/offboarding/:id/step", validate({ params, body: schema.clearance }), asyncHandler(async (req, res) => { await service.updateClearance(req.auth!, req.params.id as string, req.body.step, req.body.done); res.json({ message: "Saved." }); }));
router.post("/offboarding/:id/complete", validate({ params, body: z.object({ confirmation: z.literal("TERMINATE") }) }), asyncHandler(async (req, res) => { await service.finishOffboarding(req.auth!, req.params.id as string); res.json({ message: "Clearance completed." }); }));
router.get("/renewals", validate({ query: schema.list }), asyncHandler(async (req, res) => { res.json({ data: await service.listRenewals(req.auth!, req.query as never) }); }));
router.post("/renewals", validate({ body: schema.renewal }), asyncHandler(async (req, res) => { res.status(201).json({ data: await service.startRenewal(req.auth!, req.body) }); }));
router.put("/renewals/:id/stage", validate({ params, body: schema.renewalProgress }), asyncHandler(async (req, res) => { await service.progressRenewal(req.auth!, req.params.id as string, req.body); res.json({ message: "Saved." }); }));
router.post("/renewals/:id/complete", validate({ params, body: schema.renewalFinish }), asyncHandler(async (req, res) => { await service.finishRenewal(req.auth!, req.params.id as string, req.body); res.json({ message: "Renewed." }); }));
router.get("/renewal-candidates", asyncHandler(async (req, res) => { res.json({ data: (await getTrackableItems()).filter(i => canViewSource(req.auth!, i.sourceType)).map(i => ({ sourceType: i.sourceType, sourceId: i.recordId, title: i.labelAr, expiryDate: i.expiryDate })) }); }));
router.get("/responsible-users", asyncHandler(async (req, res) => { requireAccess(req.auth!, "tasks.create"); res.json({ data: await prisma.user.findMany({ where: { deletedAt: null, isActive: true }, select: { id: true, fullName: true }, orderBy: { fullName: "asc" }, take: 1000 }) }); }));
export default router;
