import { z } from "zod";
export const id = z.string().min(1).max(150);
export const text = z.string().trim().min(1).max(200);
export const notes = z.string().trim().max(2000).optional();
export const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v => Number.isFinite(Date.parse(v)) && new Date(v).toISOString().slice(0, 10) === v, "Invalid calendar date");
export const money = z.number().finite().min(0).max(9999999999.99).refine(v => Math.abs(v * 100 - Math.round(v * 100)) < 0.0001, "Use at most two decimal places");
export const list = z.object({ q: z.string().trim().max(100).default(""), page: z.coerce.number().int().min(1).max(100000).default(1) });
export const asset = z.object({ code: text.max(60), name: text, category: text.max(80), serialNumber: text.optional(), branchId: id.optional(), purchaseValue: money.default(0), notes });
export const assign = z.object({ employeeId: id, issuedCondition: text, notes });
export const returned = z.object({ returnedCondition: text, state: z.enum(["AVAILABLE", "MAINTENANCE", "RETIRED"]).default("AVAILABLE"), notes });
export const assetState = z.object({ state: z.enum(["AVAILABLE", "MAINTENANCE", "RETIRED"]) });
export const offboarding = z.object({ employeeId: id, plannedDate: date, reason: text });
export const clearanceSteps = ["documents", "settlement", "access", "handover"] as const;
export const clearance = z.object({ step: z.enum(clearanceSteps), done: z.boolean() });
export const renewalSources = ["EMPLOYEE_IQAMA", "EMPLOYEE_PASSPORT", "EMPLOYEE_DOCUMENT", "COMPANY_DOCUMENT"] as const;
export const renewal = z.object({ sourceType: z.enum(renewalSources), sourceId: id, ownerId: id, dueDate: date, estimatedCost: money.default(0), notes });
export const renewalProgress = z.object({ status: z.enum(["OPEN", "IN_PROGRESS", "WAITING", "CANCELLED"]), notes });
export const renewalFinish = z.object({ expiryDate: date, issueDate: date.optional(), documentNumber: text.optional(), fileId: id.optional(), paymentId: id.optional() }).refine(v => !v.issueDate || v.issueDate <= v.expiryDate, "Issue date must precede expiry");
