import { Router } from "express";
import authRoutes from "@/modules/auth/auth.routes";
import branchesRoutes from "@/modules/branches/branches.routes";
import usersRoutes from "@/modules/users/users.routes";
import rolesRoutes from "@/modules/roles/roles.routes";
import filesRoutes from "@/modules/files/files.routes";
import employeesRoutes from "@/modules/employees/employees.routes";
import { makeCompanyDocumentsRouter } from "@/modules/companyDocuments/companyDocuments.routes";
import paymentsRoutes from "@/modules/payments/payments.routes";
import notificationsRoutes from "@/modules/notifications/notifications.routes";
import auditLogsRoutes from "@/modules/auditLogs/auditLogs.routes";
import settingsRoutes from "@/modules/settings/settings.routes";
import dashboardRoutes from "@/modules/dashboard/dashboard.routes";
import reportsRoutes from "@/modules/reports/reports.routes";
import importExportRoutes from "@/modules/importExport/importExport.routes";
import searchRoutes from "@/modules/search/search.routes";
import translateRoutes from "@/modules/translate/translate.routes";
import workforceDocumentsRoutes from "@/modules/workforceDocuments/workforceDocuments.routes";
import tasksRoutes from "@/modules/tasks/tasks.routes";
import pushRoutes from "@/modules/push/push.routes";
import violationsRoutes from "@/modules/violations/violations.routes";
import taxReturnsRoutes from "@/modules/taxReturns/taxReturns.routes";
import maintenanceRoutes from "@/modules/maintenance/maintenance.routes";
import productivityRoutes from "@/modules/productivity/productivity.routes";
import operationsRoutes from "@/modules/operations/operations.routes";
import { restoringSystem } from "@/modules/maintenance/backups.service";
import { ApiError } from "@/utils/apiError";

const router = Router();
router.use((_req, _res, next) => restoringSystem ? next(new ApiError(503, "MAINTENANCE", "The system is restoring a backup. Please wait.")) : next());
router.use("/maintenance", maintenanceRoutes);
router.use("/productivity", productivityRoutes);
router.use("/operations", operationsRoutes);

router.use("/auth", authRoutes);
router.use("/branches", branchesRoutes);
router.use("/users", usersRoutes);
router.use("/roles", rolesRoutes);
router.use("/files", filesRoutes);
router.use("/employees", employeesRoutes);
router.use("/workforce-documents", workforceDocumentsRoutes);
router.use("/company-documents", makeCompanyDocumentsRouter());
router.use("/payments", paymentsRoutes);
router.use("/tax-returns", taxReturnsRoutes);
router.use("/notifications", notificationsRoutes);
router.use("/audit-logs", auditLogsRoutes);
router.use("/settings", settingsRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/reports", reportsRoutes);
router.use("/import-export", importExportRoutes);
router.use("/search", searchRoutes);
router.use("/translate", translateRoutes);
router.use("/tasks", tasksRoutes);
router.use("/push", pushRoutes);
router.use("/violations", violationsRoutes);

export default router;
