import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { toast } from "sonner";
import { api, getErrorMessage } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuthStore } from "@/stores/authStore";
import { listActiveBranches } from "@/api/branches";
import { COMPANY_DOCUMENT_CATEGORIES } from "@/api/companyDocuments";
import { operationsApi } from "@/api/operations";
interface Rule { id: string; name: string; scope: "EMPLOYEE" | "BRANCH"; type: string; branchId?: string; sponsorshipOnly: boolean; requireFile: boolean; requireValid: boolean; enabled: boolean }
interface Missing { total: number; rows: { id: string; name: string; href: string; followup: null | { taskId: string; ownerName: string; dueDate: string } }[] }
const employeeTypes = ["IQAMA", "PASSPORT", "HEALTH_CERTIFICATE", "MEDICAL_INSURANCE", "EMPLOYMENT_CONTRACT", "VISA", "EXIT_REENTRY_VISA", "FINAL_EXIT_VISA", "FLIGHT_TICKET", "DRIVING_LICENSE", "OTHER"];
const blank: Omit<Rule, "id"> = { name: "", scope: "EMPLOYEE", type: "IQAMA", sponsorshipOnly: false, requireFile: true, requireValid: true, enabled: true };
const selectClass = "h-10 rounded-lg border bg-background px-3";
export default function DocumentRequirements() {
  const { i18n, t } = useTranslation(); const c = (a: string, e: string) => i18n.language.startsWith("ar") ? a : e;
  const has = useAuthStore(s => s.hasPermission), qc = useQueryClient();
  const [ruleId, setRuleId] = useState(""), [page, setPage] = useState(1), [busy, setBusy] = useState(false), [editing, setEditing] = useState<Rule | Omit<Rule, "id"> | null>(null), [target, setTarget] = useState<{ id: string; name: string } | null>(null);
  const rules = useQuery({ queryKey: ["operations", "requirements"], queryFn: async () => (await api.get<{ data: Rule[] }>("/operations/requirements")).data.data });
  const branches = useQuery({ queryKey: ["operations", "branches"], queryFn: listActiveBranches, enabled: has("branches.view") });
  const owners = useQuery({ queryKey: ["operations", "owners"], queryFn: operationsApi.owners, enabled: has("tasks.create") });
  const missing = useQuery({ queryKey: ["operations", "missing", ruleId, page], queryFn: async () => (await api.get<{ data: Missing }>(`/operations/requirements/${ruleId}/missing`, { params: { page } })).data.data, enabled: Boolean(ruleId) });
  async function save(action: () => Promise<unknown>, done?: () => void) { setBusy(true); try { await action(); await qc.invalidateQueries({ queryKey: ["operations"] }); toast.success(c("تم الحفظ", "Saved")); done?.(); } catch (e) { toast.error(getErrorMessage(e)); } finally { setBusy(false); } }
  const current = rules.data?.find(r => r.id === ruleId);
  return <div className="space-y-4"><p className="text-sm text-muted-foreground">{c("حدد المستندات المطلوبة للموظفين أو الفروع، ثم تابع النواقص بمهمة لمسؤول وموعد إنجاز. تشمل مراجعة الموظفين العاملين ومن هم في إجازة.", "Define required employee or branch documents, then assign missing-document tasks with an owner and deadline. Employee scans cover active and on-leave staff.")}</p>{has("settings.edit") && <Button onClick={() => setEditing({ ...blank })}>{c("إضافة متطلب", "Add requirement")}</Button>}
    {editing && <form className="grid gap-3 rounded-xl border p-4 md:grid-cols-2" onSubmit={e => { e.preventDefault(); const body = { ...editing }; delete (body as Partial<Rule>).id; void save(() => "id" in editing ? api.put(`/operations/requirements/${editing.id}`, body) : api.post("/operations/requirements", body), () => setEditing(null)); }}><label className="grid gap-1 text-sm">{c("اسم المتطلب", "Requirement name")}<Input required maxLength={200} value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} /></label><label className="grid gap-1 text-sm">{c("ينطبق على", "Applies to")}<select value={editing.scope} className={selectClass} onChange={e => { const scope = e.target.value as Rule["scope"]; setEditing({ ...editing, scope, type: scope === "EMPLOYEE" ? "IQAMA" : "COMMERCIAL_REGISTRATION", sponsorshipOnly: false }); }}><option value="EMPLOYEE">{c("الموظفين", "Employees")}</option><option value="BRANCH">{c("الفروع", "Branches")}</option></select></label><label className="grid gap-1 text-sm">{c("نوع المستند", "Document type")}<select value={editing.type} className={selectClass} onChange={e => setEditing({ ...editing, type: e.target.value })}>{(editing.scope === "EMPLOYEE" ? employeeTypes : COMPANY_DOCUMENT_CATEGORIES).map(type => <option value={type} key={type}>{t(`${editing.scope === "EMPLOYEE" ? "employeeDocumentTypes" : "companyDocumentCategories"}.${type}`, { defaultValue: type.replaceAll("_", " ") })}</option>)}</select></label><label className="grid gap-1 text-sm">{c("الفرع", "Branch")}<select value={editing.branchId || ""} className={selectClass} onChange={e => setEditing({ ...editing, branchId: e.target.value || undefined })}><option value="">{c("كل الفروع", "All branches")}</option>{branches.data?.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{([["requireFile", "مرفق مطلوب", "Attachment required"], ["requireValid", "المستند غير منتهي", "Document must not be expired"], ["enabled", "متطلب نشط", "Requirement enabled"]] as const).map(([key, ar, en]) => <label key={key} className="flex gap-2 text-sm"><input type="checkbox" checked={editing[key]} onChange={e => setEditing({ ...editing, [key]: e.target.checked })} />{c(ar, en)}</label>)}{editing.scope === "EMPLOYEE" && <label className="flex gap-2 text-sm"><input type="checkbox" checked={editing.sponsorshipOnly} onChange={e => setEditing({ ...editing, sponsorshipOnly: e.target.checked })} />{c("الموظفون على الكفالة فقط", "Sponsored employees only")}</label>}<div className="flex gap-2"><Button disabled={busy}>{c("حفظ", "Save")}</Button><Button type="button" variant="outline" disabled={busy} onClick={() => setEditing(null)}>{c("إلغاء", "Cancel")}</Button></div></form>}
    {rules.isError && <p role="alert">{getErrorMessage(rules.error)}</p>}<div className="flex flex-wrap gap-2">{rules.data?.map(r => <div key={r.id} className="flex items-center gap-1"><Button variant={ruleId === r.id ? "default" : "outline"} disabled={!r.enabled} onClick={() => { setRuleId(r.id); setPage(1); setTarget(null); }}>{r.name}{!r.enabled && ` · ${c("متوقف", "Disabled")}`}</Button>{has("settings.edit") && <Button variant="ghost" onClick={() => setEditing({ ...r })}>{c("تعديل", "Edit")}</Button>}</div>)}</div>{current && <p className="text-sm">{current.name} · {missing.data?.total ?? "…"} {c("سجل بحاجة لاستكمال مستنداته", "records missing required documents")}</p>}{missing.isFetching && <p>{c("جاري مراجعة المستندات…", "Checking documents…")}</p>}{missing.isError && <p role="alert">{getErrorMessage(missing.error)}</p>}{missing.data?.rows.map(row => <div key={row.id} className="flex flex-wrap justify-between gap-3 rounded-xl border bg-card p-4"><div><Link className="font-semibold text-primary" to={row.href}>{row.name}</Link>{row.followup && <p className="text-sm">{row.followup.ownerName} · {row.followup.dueDate} · <Link className="text-primary underline" to={`/daily-tasks?date=${row.followup.dueDate}`}>{c("المهمة المرتبطة", "Linked task")}</Link></p>}</div>{has("tasks.create") && <Button variant="outline" onClick={() => setTarget({ id: row.id, name: row.name })}>{c("إسناد متابعة", "Assign follow-up")}</Button>}</div>)}
    {target && <form className="grid gap-3 rounded-xl border p-4" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void save(() => api.post("/operations/requirements/followup", { ruleId, targetId: target.id, ownerId: f.get("owner"), dueDate: f.get("due") }), () => setTarget(null)); }}><p className="font-semibold">{target.name}</p><label className="grid gap-1 text-sm">{c("المسؤول", "Responsible user")}<select className={selectClass} name="owner" required><option value="">{c("اختر المسؤول", "Select owner")}</option>{owners.data?.map(u => <option key={u.id} value={u.id}>{u.fullName}</option>)}</select></label><label className="grid gap-1 text-sm">{c("موعد الإنجاز", "Deadline")}<Input type="date" name="due" required /></label>{owners.isError && <p role="alert">{getErrorMessage(owners.error)}</p>}<div className="flex gap-2"><Button disabled={busy}>{c("إنشاء المهمة", "Create task")}</Button><Button type="button" variant="outline" onClick={() => setTarget(null)}>{c("إلغاء", "Cancel")}</Button></div></form>}
    {(missing.data?.total || 0) > 20 && <div className="flex justify-center gap-3"><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>{c("السابق", "Previous")}</Button><span>{page} / {Math.ceil((missing.data?.total || 0) / 20)}</span><Button variant="outline" disabled={page * 20 >= (missing.data?.total || 0)} onClick={() => setPage(page + 1)}>{c("التالي", "Next")}</Button></div>}
  </div>;
}
