import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from "recharts";
import { api, getErrorMessage } from "@/lib/api";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { useAuthStore } from "@/stores/authStore";
import { listActiveBranches } from "@/api/branches";
interface Bucket { id: string; name: string; current: number; previous: number; count: number }
interface Overview { total: number; previousTotal: number; count: number; from: string; to: string; previousFrom: string; previousTo: string; branches: Bucket[]; employees: Bucket[]; categories: Bucket[]; months: { month: string; total: number }[]; duplicates: { id: string; number: string; date: string; total: string; reference: string | null; supplier: string | null }[][] }
export default function FinanceOverview() {
  const { i18n, t } = useTranslation(); const ar = i18n.language.startsWith("ar"), c = (a: string, e: string) => ar ? a : e;
  const has = useAuthStore(s => s.hasPermission); const today = new Date().toISOString().slice(0, 10);
  const [from, setFrom] = useState(today.slice(0, 4) + "-01-01"), [to, setTo] = useState(today), [branchId, setBranchId] = useState("");
  const [filter, setFilter] = useState({ from, to, branchId }); const [group, setGroup] = useState<"branches" | "employees" | "categories">("branches"), [page, setPage] = useState(1);
  const branches = useQuery({ queryKey: ["operations", "branches"], queryFn: listActiveBranches, enabled: has("branches.view") });
  const query = useQuery({ queryKey: ["operations", "finance", filter], queryFn: async () => (await api.get<{ data: Overview }>("/operations/finance", { params: { ...filter, branchId: filter.branchId || undefined } })).data.data });
  const money = (value: number) => new Intl.NumberFormat(ar ? "ar-SA" : "en-SA", { style: "currency", currency: "SAR" }).format(value);
  const data = query.data; const rows = data?.[group] || [];
  return <div className="space-y-5"><form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); setFilter({ from, to, branchId }); setPage(1); }}><label className="grid gap-1 text-sm">{c("من", "From")}<Input type="date" required value={from} onChange={e => setFrom(e.target.value)} /></label><label className="grid gap-1 text-sm">{c("إلى", "To")}<Input type="date" required value={to} onChange={e => setTo(e.target.value)} /></label><label className="grid gap-1 text-sm">{c("الفرع", "Branch")}<select className="h-10 rounded-lg border bg-background px-3" value={branchId} onChange={e => setBranchId(e.target.value)}><option value="">{c("كل الفروع", "All branches")}</option>{branches.data?.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}</select></label><Button disabled={query.isFetching}>{c("عرض المقارنة", "Compare")}</Button></form>
    {query.isPending && <p>{c("جاري التحميل…", "Loading…")}</p>}{query.isError && <p role="alert">{getErrorMessage(query.error)}</p>}{data && <><div className="grid gap-4 md:grid-cols-3">{[[c("إجمالي المصروفات", "Total spending"), money(data.total)], [c("الفترة السابقة", "Previous period"), money(data.previousTotal)], [c("الفرق", "Difference"), money(data.total - data.previousTotal)]].map(([label, value]) => <div key={label} className="rounded-xl border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div><p className="text-sm text-muted-foreground">{data.count} {c("دفعة؛ المقارنة مع", "payments; compared with")} {data.previousFrom} — {data.previousTo}. {c("المبالغ تشمل الضريبة.", "Amounts include VAT.")}</p>
    <div className="rounded-xl border bg-card p-4"><p className="mb-4 font-semibold">{c("اتجاه المصروفات الشهري", "Monthly spending trend")}</p>{data.months.length ? <div className="h-64" dir="ltr"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.months}><XAxis dataKey="month" /><YAxis /><Tooltip formatter={value => money(Number(value))} /><Bar dataKey="total" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div> : <p>{c("لا توجد مدفوعات في الفترة", "No payments in this period")}</p>}</div>
    <div className="flex gap-2">{(["branches", "employees", "categories"] as const).map(g => <Button key={g} variant={g === group ? "default" : "outline"} onClick={() => { setGroup(g); setPage(1); }}>{g === "branches" ? c("الفروع", "Branches") : g === "employees" ? c("الموظفون", "Employees") : c("التصنيفات", "Categories")}</Button>)}</div><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b bg-muted/40">{[c("الاسم", "Name"), c("الحالية", "Current"), c("السابقة", "Previous"), c("الفرق", "Difference"), c("عدد الدفعات", "Payments")].map(h => <th className="p-3 text-start" key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice((page - 1) * 20, page * 20).map(r => <tr key={r.id} className="border-b"><td className="p-3">{group === "categories" ? t(`paymentCategories.${r.name}`, { defaultValue: r.name }) : r.name}</td><td className="p-3">{money(r.current)}</td><td className="p-3">{money(r.previous)}</td><td className="p-3">{money(r.current - r.previous)}</td><td className="p-3">{r.count}</td></tr>)}</tbody></table></div>{rows.length > 20 && <div className="flex justify-center gap-3"><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>{c("السابق", "Previous")}</Button><span>{page} / {Math.ceil(rows.length / 20)}</span><Button variant="outline" disabled={page * 20 >= rows.length} onClick={() => setPage(page + 1)}>{c("التالي", "Next")}</Button></div>}
    <div className="space-y-3 rounded-xl border bg-card p-4"><p className="font-semibold">{c("مدفوعات محتمل تكرارها", "Possible duplicate payments")} · {data.duplicates.length}</p><p className="text-sm text-muted-foreground">{c("تشابه التاريخ والمبلغ والمستفيد والمرجع يستدعي المراجعة؛ لا يتم حذف أو دمج أي دفعة تلقائيًا.", "Matching date, amount, counterparty and reference warrant review; no payments are automatically deleted or merged.")}</p>{data.duplicates.slice(0, 50).map((group, index) => <div className="flex flex-wrap gap-3 border-t pt-3" key={index}>{group.map(p => <Link className="text-sm text-primary underline" key={p.id} to={`/payments?q=${encodeURIComponent(p.number)}`}>{p.number} · {money(Number(p.total))} · {p.supplier || p.reference || "—"}</Link>)}</div>)}{data.duplicates.length > 50 && <p>{c("أول 50 مجموعة؛ ضيق الفترة لرؤية بقية الحالات.", "First 50 groups; narrow the period to review remaining cases.")}</p>}</div></>}
  </div>;
}
