import { lazy, Suspense, useState, type ReactNode } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useQuery, useQueryClient, useIsFetching } from "@tanstack/react-query";
import { toast } from "sonner";
import { PageHeader } from "@/components/common/page-header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ConfirmDialog } from "@/components/common/confirm-dialog";
import { useAuthStore } from "@/stores/authStore";
import { getErrorMessage } from "@/lib/api";
import { operationsApi, type Asset, type Renewal } from "@/api/operations";
import { employeesApi } from "@/api/employees";
import { paymentsApi } from "@/api/payments";
import { listActiveBranches } from "@/api/branches";
import { openPdfInNewTab } from "@/lib/download";
const FinanceOverview = lazy(() => import("./finance-overview"));
const DocumentRequirements = lazy(() => import("./document-requirements"));
function useCopy() { const { i18n } = useTranslation(); return (a: string, e: string) => i18n.language.startsWith("ar") ? a : e; }
function Field({ title, children }: { title: string; children: ReactNode }) { return <label className="grid gap-1 text-sm"><span>{title}</span>{children}</label>; }
const selectClass = "h-10 rounded-lg border bg-background px-3";
const statuses: Record<string, [string, string]> = { AVAILABLE: ["متاحة", "Available"], ASSIGNED: ["مسلّمة", "Assigned"], MAINTENANCE: ["صيانة", "Maintenance"], RETIRED: ["مستبعدة", "Retired"], OPEN: ["مفتوح", "Open"], IN_PROGRESS: ["قيد التنفيذ", "In progress"], WAITING: ["بانتظار إجراء", "Waiting"], CANCELLED: ["ملغى", "Cancelled"], COMPLETED: ["مكتمل", "Completed"] };
function useActions() {
  const qc = useQueryClient(), c = useCopy(); const [busy, setBusy] = useState(false);
  async function run(action: () => Promise<unknown>, after?: () => void) { setBusy(true); try { await action(); await qc.invalidateQueries({ queryKey: ["operations"] }); toast.success(c("تم الحفظ", "Saved")); after?.(); } catch (e) { toast.error(getErrorMessage(e)); } finally { setBusy(false); } }
  return { busy, run };
}
function EmployeeSelect({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const c = useCopy(); const [q, setQ] = useState("");
  const query = useQuery({ queryKey: ["operations", "employee-options", q], queryFn: () => employeesApi.list({ q, pageSize: 20 }) });
  return <Field title={c("الموظف", "Employee")}><Input aria-label={c("ابحث عن الموظف", "Search employee")} value={q} onChange={e => setQ(e.target.value)} placeholder={c("بحث بالاسم أو الرقم", "Search name or number")} /><select required value={value} className={selectClass} onChange={e => onChange(e.target.value)}><option value="">{c("اختر الموظف", "Select employee")}</option>{query.data?.data.map(e => <option key={e.id} value={e.id}>{e.fullNameAr} · {e.employeeNumber}</option>)}</select>{query.isError && <p role="alert">{getErrorMessage(query.error)}</p>}</Field>;
}
function Assets({ search, page }: { search: string; page: number }) {
  const c = useCopy(), has = useAuthStore(s => s.hasPermission); const { busy, run } = useActions();
  const query = useQuery({ queryKey: ["operations", "assets", search, page], queryFn: () => operationsApi.assets(search, page) });
  const branches = useQuery({ queryKey: ["operations", "branches"], queryFn: listActiveBranches, enabled: has("branches.view") });
  const [creating, setCreating] = useState(false), [selected, setSelected] = useState<Asset | null>(null), [employee, setEmployee] = useState(""), [condition, setCondition] = useState(""), [returnState, setReturnState] = useState("AVAILABLE"), [historyId, setHistoryId] = useState("");
  const history = useQuery({ queryKey: ["operations", "history", historyId], queryFn: () => operationsApi.history(historyId), enabled: Boolean(historyId) });
  return <div className="space-y-4">{has("employees.edit") && <Button onClick={() => setCreating(v => !v)}>{c("إضافة عهدة", "Add asset")}</Button>}
    {creating && <form className="grid gap-3 rounded-xl border p-4 md:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(() => operationsApi.save("/assets", { code: f.get("code"), name: f.get("name"), category: f.get("category"), serialNumber: f.get("serial") || undefined, branchId: f.get("branch") || undefined, purchaseValue: Number(f.get("value")), notes: f.get("notes") }), () => setCreating(false)); }}>
      <Field title={c("كود العهدة", "Asset code")}><Input name="code" required maxLength={60} /></Field><Field title={c("اسم العهدة", "Asset name")}><Input name="name" required maxLength={200} /></Field><Field title={c("التصنيف", "Category")}><Input name="category" required maxLength={80} /></Field><Field title={c("الرقم التسلسلي", "Serial number")}><Input name="serial" maxLength={200} /></Field><Field title={c("الفرع", "Branch")}><select name="branch" className={selectClass}><option value="">{c("بدون فرع", "No branch")}</option>{branches.data?.map(b => <option value={b.id} key={b.id}>{b.name}</option>)}</select></Field>{has("payments.view") && <Field title={c("قيمة الشراء", "Purchase value")}><Input name="value" type="number" min={0} step="0.01" defaultValue={0} required /></Field>}<Field title={c("ملاحظات", "Notes")}><Input name="notes" maxLength={2000} /></Field><Button disabled={busy} type="submit">{c("حفظ", "Save")}</Button>
    </form>}
    {query.isPending && <p>{c("جاري التحميل…", "Loading…")}</p>}{query.isError && <p role="alert">{getErrorMessage(query.error)}</p>}
    {query.data?.rows.map(a => <div className="rounded-xl border bg-card p-4" key={a.id}><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{a.code} · {a.name}</p><p className="text-sm text-muted-foreground">{a.category} · {c(...statuses[a.state])} · {a.serialNumber || "—"}</p>{a.handovers.map(h => <Link key={h.id} className="text-sm text-primary" to={`/employees/${h.employee.id}`}>{h.employee.fullNameAr}</Link>)}</div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => setHistoryId(a.id)}>{c("سجل التسليم والطباعة", "History & printing")}</Button>{has("employees.edit") && (a.state === "AVAILABLE" || a.handovers.length > 0) && <Button disabled={busy} onClick={() => { setSelected(a); setEmployee(""); setCondition(""); }}>{a.handovers.length ? c("استرجاع", "Return") : c("تسليم", "Issue")}</Button>}{has("employees.edit") && !a.handovers.length && <select aria-label={c("حالة العهدة", "Asset state")} className={selectClass} disabled={busy} value={a.state} onChange={e => void run(() => operationsApi.update(`/assets/${a.id}/state`, { state: e.target.value }))}>{["AVAILABLE", "MAINTENANCE", "RETIRED"].map(s => <option key={s} value={s}>{c(...statuses[s])}</option>)}</select>}</div></div></div>)}
    {selected && <form className="grid gap-3 rounded-xl border p-4" onSubmit={e => { e.preventDefault(); void run(() => selected.handovers.length ? operationsApi.save(`/handovers/${selected.handovers[0].id}/return`, { returnedCondition: condition, state: returnState }) : operationsApi.save(`/assets/${selected.id}/assign`, { employeeId: employee, issuedCondition: condition }), () => setSelected(null)); }}><p className="font-semibold">{selected.name}</p>{!selected.handovers.length && <EmployeeSelect value={employee} onChange={setEmployee} />}<Field title={c("حالة العهدة عند التسليم/الاسترجاع", "Condition at issue/return")}><Input required maxLength={200} value={condition} onChange={e => setCondition(e.target.value)} /></Field>{selected.handovers.length > 0 && <Field title={c("الحالة بعد الاسترجاع", "State after return")}><select className={selectClass} value={returnState} onChange={e => setReturnState(e.target.value)}>{["AVAILABLE", "MAINTENANCE", "RETIRED"].map(s => <option key={s} value={s}>{c(...statuses[s])}</option>)}</select></Field>}<div className="flex gap-2"><Button disabled={busy} type="submit">{c("تسجيل", "Record")}</Button><Button variant="outline" type="button" onClick={() => setSelected(null)}>{c("إلغاء", "Cancel")}</Button></div></form>}
    {historyId && <div className="space-y-3 rounded-xl border p-4"><Button variant="outline" onClick={() => setHistoryId("")}>{c("إغلاق السجل", "Close history")}</Button>{history.isError && <p role="alert">{getErrorMessage(history.error)}</p>}{history.data?.map(h => <div key={h.id} className="flex flex-wrap justify-between gap-2 border-b pb-2"><p>{h.employee.fullNameAr} · {h.issuedAt.slice(0, 10)} · {h.returnedAt ? c("استرجعت", "Returned") : c("مسلّمة", "Assigned")}</p>{has("employees.export") && <Button variant="outline" onClick={() => void openPdfInNewTab(`/operations/handovers/${h.id}/pdf`).catch(e => toast.error(getErrorMessage(e)))}>{c("محضر PDF", "PDF receipt")}</Button>}</div>)}</div>}
    <p className="text-sm text-muted-foreground">{query.data?.total ?? 0} {c("عهدة", "assets")}</p>
  </div>;
}
function Clearances({ search, page }: { search: string; page: number }) {
  const c = useCopy(), has = useAuthStore(s => s.hasPermission); const { busy, run } = useActions();
  const query = useQuery({ queryKey: ["operations", "offboarding", search, page], queryFn: () => operationsApi.clearances(search, page) });
  const [creating, setCreating] = useState(false), [employee, setEmployee] = useState(""), [confirm, setConfirm] = useState("");
  const steps: Record<string, [string, string]> = { documents: ["تسليم المستندات", "Documents returned"], settlement: ["التسوية المالية", "Financial settlement"], access: ["إلغاء صلاحيات الموظف", "Employee access revoked"], handover: ["تسليم الأعمال", "Work handed over"] };
  return <div className="space-y-4">{has("employees.edit") && <Button onClick={() => setCreating(v => !v)}>{c("بدء إخلاء طرف", "Start clearance")}</Button>}{creating && <form className="grid gap-3 rounded-xl border p-4" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(() => operationsApi.save("/offboarding", { employeeId: employee, plannedDate: f.get("date"), reason: f.get("reason") }), () => { setCreating(false); setEmployee(""); }); }}><EmployeeSelect value={employee} onChange={setEmployee} /><Field title={c("تاريخ انتهاء الخدمة المخطط", "Planned departure date")}><Input type="date" name="date" required /></Field><Field title={c("السبب", "Reason")}><Input name="reason" required maxLength={200} /></Field><Button disabled={busy}>{c("بدء المتابعة", "Start tracking")}</Button></form>}
    {query.isError && <p role="alert">{getErrorMessage(query.error)}</p>}{query.isPending && <p>{c("جاري التحميل…", "Loading…")}</p>}{query.data?.rows.map(r => <div key={r.id} className="space-y-3 rounded-xl border bg-card p-4"><Link to={`/employees/${r.employee.id}`} className="font-semibold text-primary">{r.employee.fullNameAr} · {r.employee.employeeNumber}</Link><p className="text-sm">{r.plannedDate.slice(0, 10)} · {r.reason} · {c(...statuses[r.status])}</p>{Object.entries(steps).map(([step, label]) => <label key={step} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={r.steps[step] === true} disabled={busy || r.status !== "OPEN" || !has("employees.edit") || (step === "settlement" && !has("payments.view"))} onChange={e => void run(() => operationsApi.update(`/offboarding/${r.id}/step`, { step, done: e.target.checked }))} />{c(...label)}</label>)}<p className="text-sm">{c("العُهد المتبقية", "Outstanding assets")}: {r.employee.assetHandovers.map(h => `${h.asset?.code} ${h.asset?.name}`).join("، ") || c("لا توجد", "None")}</p>{r.status === "OPEN" && has("employees.edit") && has("payments.view") && <Button disabled={busy || r.employee.assetHandovers.length > 0 || Object.keys(steps).some(s => !r.steps[s])} onClick={() => setConfirm(r.id)}>{c("إكمال إخلاء الطرف", "Complete clearance")}</Button>}</div>)}
    <ConfirmDialog open={Boolean(confirm)} onOpenChange={v => { if (!v) setConfirm(""); }} title={c("إكمال إخلاء الطرف", "Complete clearance")} description={c("سيتم تسجيل إخلاء الطرف وتغيير حالة الموظف إلى انتهت خدمته، مع الاحتفاظ بملفه وتاريخه. تأكد من تنفيذ التسوية وإلغاء صلاحياته فعليًا.", "Records clearance and changes the employee status to terminated, retaining their history. Confirm settlement and access revocation have actually been completed.")} confirmLabel={c("تأكيد انتهاء الخدمة", "Confirm termination")} loading={busy} onConfirm={() => void run(() => operationsApi.save(`/offboarding/${confirm}/complete`, { confirmation: "TERMINATE" }), () => setConfirm(""))} />
    <p className="text-sm text-muted-foreground">{query.data?.total ?? 0} {c("حالة", "cases")}</p>
  </div>;
}
function Renewals({ search, page }: { search: string; page: number }) {
  const c = useCopy(), has = useAuthStore(s => s.hasPermission); const { busy, run } = useActions(); const canStart = has("tasks.create");
  const query = useQuery({ queryKey: ["operations", "renewals", search, page], queryFn: () => operationsApi.renewals(search, page) });
  const candidates = useQuery({ queryKey: ["operations", "candidates"], queryFn: operationsApi.candidates, enabled: canStart });
  const owners = useQuery({ queryKey: ["operations", "owners"], queryFn: operationsApi.owners, enabled: canStart });
  const [paymentSearch, setPaymentSearch] = useState("");
  const payments = useQuery({ queryKey: ["operations", "payments", paymentSearch], queryFn: () => paymentsApi.list({ q: paymentSearch, pageSize: 20 }), enabled: has("payments.view") });
  const [creating, setCreating] = useState(false), [selected, setSelected] = useState<Renewal | null>(null);
  return <div className="space-y-4">{canStart && <Button onClick={() => setCreating(v => !v)}>{c("بدء تجديد", "Start renewal")}</Button>}{creating && <form className="grid gap-3 rounded-xl border p-4 md:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget), candidate = candidates.data?.find(v => `${v.sourceType}:${v.sourceId}` === f.get("source")); if (!candidate) return; void run(() => operationsApi.save("/renewals", { sourceType: candidate.sourceType, sourceId: candidate.sourceId, ownerId: f.get("owner"), dueDate: f.get("due"), estimatedCost: Number(f.get("cost") || 0), notes: f.get("notes") }), () => setCreating(false)); }}><Field title={c("المستند", "Document")}><select name="source" required className={selectClass}><option value="">{c("اختر المستند", "Select document")}</option>{candidates.data?.map(v => <option key={`${v.sourceType}:${v.sourceId}`} value={`${v.sourceType}:${v.sourceId}`}>{v.title} · {v.expiryDate.slice(0, 10)}</option>)}</select></Field><Field title={c("المسؤول", "Responsible user")}><select name="owner" className={selectClass} required><option value="">{c("اختر المسؤول", "Select owner")}</option>{owners.data?.map(v => <option key={v.id} value={v.id}>{v.fullName}</option>)}</select></Field><Field title={c("موعد الإنجاز", "Deadline")}><Input name="due" type="date" required /></Field>{has("payments.view") && <Field title={c("التكلفة المتوقعة", "Estimated cost")}><Input name="cost" type="number" min={0} step="0.01" defaultValue={0} /></Field>}<Field title={c("ملاحظات", "Notes")}><Input name="notes" maxLength={2000} /></Field><Button disabled={busy}>{c("إنشاء التجديد والمهمة", "Create renewal & task")}</Button>{(candidates.isError || owners.isError) && <p role="alert">{getErrorMessage(candidates.error || owners.error)}</p>}</form>}
    {query.isError && <p role="alert">{getErrorMessage(query.error)}</p>}{query.isPending && <p>{c("جاري التحميل…", "Loading…")}</p>}{query.data?.rows.map(r => <div key={r.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-card p-4"><div><p className="font-semibold">{r.title}</p><p className="text-sm">{r.owner.fullName} · {r.dueDate.slice(0, 10)} · {c(...statuses[r.status])}{r.estimatedCost !== undefined && ` · ${r.estimatedCost}`}</p>{r.taskId && <Link className="text-sm text-primary" to="/daily-tasks">{c("المهمة المرتبطة", "Linked task")}</Link>}</div>{!["COMPLETED", "CANCELLED"].includes(r.status) && has(`${r.sourceType === "COMPANY_DOCUMENT" ? "companyDocuments" : r.sourceType === "EMPLOYEE_DOCUMENT" ? "employeeDocuments" : "employees"}.edit`) && <div className="flex gap-2"><select className={selectClass} aria-label={c("مرحلة التجديد", "Renewal stage")} value={r.status} disabled={busy} onChange={e => void run(() => operationsApi.update(`/renewals/${r.id}/stage`, { status: e.target.value }))}>{["OPEN", "IN_PROGRESS", "WAITING"].map(s => <option key={s} value={s}>{c(...statuses[s])}</option>)}</select><Button disabled={busy} onClick={() => setSelected(r)}>{c("استلام المستند المجدد", "Receive renewed document")}</Button></div>}</div>)}
    {selected && <form className="grid gap-3 rounded-xl border p-4 md:grid-cols-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void run(() => operationsApi.save(`/renewals/${selected.id}/complete`, { expiryDate: f.get("expiry"), issueDate: f.get("issue") || undefined, documentNumber: f.get("number") || undefined, paymentId: f.get("payment") || undefined }), () => setSelected(null)); }}><p className="md:col-span-2 font-semibold">{selected.title}</p><p className="md:col-span-2 text-sm text-muted-foreground">{c("سيتم تحديث تاريخ المستند وحفظ نسخته السابقة وإكمال المهمة المرتبطة. ارفع المرفق الجديد من صفحة المستند.", "Updates the document, retains its previous revision and completes the linked task. Upload the new attachment from the document page.")}</p><Field title={c("تاريخ الانتهاء الجديد", "New expiry date")}><Input name="expiry" type="date" required /></Field><Field title={c("تاريخ الإصدار", "Issue date")}><Input name="issue" type="date" /></Field><Field title={c("رقم المستند الجديد إن تغير", "New document number if changed")}><Input name="number" maxLength={200} /></Field>{has("payments.view") && <Field title={c("الدفعة المرتبطة (اختياري)", "Linked payment (optional)")}><Input value={paymentSearch} onChange={e => setPaymentSearch(e.target.value)} placeholder={c("بحث في المدفوعات", "Search payments")} /><select name="payment" className={selectClass}><option value="">{c("بدون ربط", "No linked payment")}</option>{payments.data?.data.map(p => <option value={p.id} key={p.id}>{p.paymentNumber} · {p.description || p.category} · {p.total}</option>)}</select>{payments.isError && <p role="alert">{getErrorMessage(payments.error)}</p>}</Field>}<div className="flex gap-2"><Button disabled={busy}>{c("إكمال التجديد", "Complete renewal")}</Button><Button type="button" variant="outline" onClick={() => setSelected(null)}>{c("إلغاء", "Cancel")}</Button></div></form>}
    <p className="text-sm text-muted-foreground">{query.data?.total ?? 0} {c("تجديد", "renewals")}</p>
  </div>;
}
export default function OperationsPage() {
  const c = useCopy(), has = useAuthStore(s => s.hasPermission); const [params, setParams] = useSearchParams();
  const tab = ["assets", "offboarding", "renewals", "finance", "requirements"].includes(params.get("tab") || "") ? params.get("tab")! : "assets";
  const [search, setSearch] = useState(""), [page, setPage] = useState(1);
  const fetching = useIsFetching({ queryKey: ["operations", tab, search, page] });
  const cache = useQueryClient(); const total = cache.getQueryData<{ total: number }>(["operations", tab, search, page])?.total ?? 0;
  const paged = ["assets", "offboarding", "renewals"].includes(tab);
  return <div className="space-y-5"><PageHeader title={c("العُهد والتجديدات", "Assets & renewals")} description={c("متابعة العُهد وإخلاء الطرف وتجديد المستندات", "Track assets, clearance and document renewals")} /><div className="flex flex-wrap gap-2">{([["assets", "العُهد", "Assets"], ["offboarding", "إخلاء الطرف", "Clearance"], ["renewals", "التجديدات", "Renewals"], ["finance", "تحليل التكاليف", "Cost analysis"], ["requirements", "نواقص المستندات", "Missing documents"]] as const).filter(v => v[0] === "finance" ? has("payments.view") : v[0] === "requirements" ? (has("employeeDocuments.view") || has("companyDocuments.view")) : v[0] === "renewals" || has("employees.view")).map(v => <Button key={v[0]} variant={tab === v[0] ? "default" : "outline"} onClick={() => { setParams({ tab: v[0] }); setPage(1); setSearch(""); }}>{c(v[1], v[2])}</Button>)}</div>{paged && <Input aria-label={c("بحث", "Search")} placeholder={c("بحث في السجلات", "Search records")} value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} />}{tab === "requirements" ? <Suspense fallback={<p>{c("جاري التحميل…", "Loading…")}</p>}><DocumentRequirements /></Suspense> : tab === "finance" ? has("payments.view") ? <Suspense fallback={<p>{c("جاري التحميل…", "Loading…")}</p>}><FinanceOverview /></Suspense> : <p>{c("ليست لديك صلاحية المدفوعات", "Payments permission required")}</p> : tab !== "renewals" && !has("employees.view") ? <p>{c("ليست لديك صلاحية عرض الموظفين", "Employee view permission required")}</p> : tab === "assets" ? <Assets search={search} page={page} /> : tab === "offboarding" ? <Clearances search={search} page={page} /> : <Renewals search={search} page={page} />}{paged && <div className="flex items-center justify-center gap-3"><Button variant="outline" disabled={page === 1} onClick={() => setPage(v => v - 1)}>{c("السابق", "Previous")}</Button><span>{page} / {Math.max(1, Math.ceil(total / 20))}</span><Button variant="outline" disabled={fetching > 0 || page * 20 >= total} onClick={() => setPage(v => v + 1)}>{c("التالي", "Next")}</Button></div>}</div>;
}
