ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'COMMERCIAL_REGISTRATION';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'MUNICIPAL_LICENSE';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'TOBACCO_LICENSE';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'PERMIT_24H';
