ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'RENT_PAYMENT';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'INTERNET';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'ELECTRICITY';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'WATER';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'MAINTENANCE';
ALTER TYPE "PaymentCategory" ADD VALUE IF NOT EXISTS 'PURCHASES';
