import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useSearchParams } from "react-router-dom";
import { toast } from "sonner";
import { Archive, History, Trash2, RotateCcw, Download, Loader2, Upload, ShieldCheck } from "lucide-react";
import { maintenanceApi, type TrashKind, type BackupItem } from "@/api/maintenance";
import { useAuthStore } from "@/stores/authStore";
import { getErrorMessage, extractErrorMessage, keepRefreshToken } from "@/lib/api";
import { filesApi } from "@/api/files";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
const kinds: [TrashKind, string, string, string][] = [["employee", "الموظفون", "Employees", "employees"], ["companyDocument", "مستندات الشركة", "Company documents", "companyDocuments"], ["employeeDocument", "وثائق الموظفين", "Employee documents", "employeeDocuments"], ["payment", "المدفوعات", "Payments", "payments"], ["branch", "المؤسسات", "Branches", "branches"], ["user", "حسابات المستخدمين", "User accounts", "users"]];
function Pages({ page, total, setPage, isAr }: { page: number; total: number; setPage: (n: number) => void; isAr: boolean }) { return <div className="flex items-center justify-between gap-2 pt-3"><Button variant="outline" disabled={page === 1} onClick={() => setPage(page - 1)}>{isAr ? "السابق" : "Previous"}</Button><small>{page} / {Math.max(1, Math.ceil(total / 30))}</small><Button variant="outline" disabled={page * 30 >= total} onClick={() => setPage(page + 1)}>{isAr ? "التالي" : "Next"}</Button></div>; }
function TrashPanel({ isAr }: { isAr: boolean }) {
  const has = useAuthStore(s => s.hasPermission), admin = useAuthStore(s => s.user?.isSuperAdmin), cache = useQueryClient();
  const allowed = kinds.filter(([kind, , , module]) => has(`${module}.view`) && has(`${module}.delete`) && (kind !== "user" || admin));
  const [kind, setKind] = useState<TrashKind>(allowed[0]?.[0] ?? "employee"), [page, setPage] = useState(1), [busy, setBusy] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["trash", kind, page], queryFn: () => maintenanceApi.trash(kind, page), enabled: allowed.some(k => k[0] === kind) });
  const module = kinds.find(k => k[0] === kind)![3];
  async function restore(id: string) { setBusy(id); try { await maintenanceApi.restoreTrash(kind, id); await cache.invalidateQueries(); toast.success(isAr ? "تم استرجاع السجل." : "Record restored."); } catch (error) { toast.error(getErrorMessage(error)); } finally { setBusy(null); } }
  return <Card><CardHeader><CardTitle>{isAr ? "سلة المحذوفات" : "Recycle bin"}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{isAr ? "استرجع السجلات المحذوفة بصلاحياتك الحالية. استرجع المؤسسة أو الموظف أولًا إذا كان السجل مرتبطًا به. حسابات المستخدمين المسترجعة تظل غير نشطة لحين تفعيلها من الإدارة." : "Restore records using your existing permissions. Restore a deleted parent branch or employee first. Restored user accounts remain inactive until enabled by an administrator."}</p>
    {!allowed.length ? <p>{isAr ? "لا توجد أنواع محذوفات متاحة لصلاحياتك." : "No recycle bin categories available for your permissions."}</p> : <><select aria-label={isAr ? "نوع السجلات" : "Record type"} className="w-full rounded-xl border bg-background p-3" value={kind} onChange={e => { setKind(e.target.value as TrashKind); setPage(1); }}>{allowed.map(([id, ar, en]) => <option key={id} value={id}>{isAr ? ar : en}</option>)}</select>
    {query.isPending ? <Loader2 className="animate-spin" /> : query.isError ? <Button onClick={() => query.refetch()}>{isAr ? "تعذّر التحميل — إعادة المحاولة" : "Could not load — retry"}</Button> : query.data?.rows.length ? query.data.rows.map(row => <div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><b className="break-words text-sm">{row.name}</b><p className="break-words text-xs text-muted-foreground">{row.reference}</p><small className="text-muted-foreground">{new Date(row.deletedAt).toLocaleString(isAr ? "ar-SA" : "en-GB")}</small></div><Button size="sm" disabled={!!busy || !has(`${module}.edit`)} onClick={() => restore(row.id)}>{busy === row.id ? <Loader2 size={14} className="animate-spin" /> : <RotateCcw size={14} />}{isAr ? "استرجاع" : "Restore"}</Button></div>) : <p className="py-5 text-center text-sm text-muted-foreground">{isAr ? "لا توجد سجلات محذوفة." : "No deleted records."}</p>}<Pages page={page} total={query.data?.total ?? 0} setPage={setPage} isAr={isAr} /></>}
  </CardContent></Card>;
}
const labels: Record<string, string> = { name: "الاسم", category: "التصنيف", type: "النوع", documentNumber: "رقم الوثيقة", licenseNumber: "رقم الترخيص", issuingAuthority: "جهة الإصدار", issueDate: "الإصدار", startDate: "البداية", expiryDate: "الانتهاء", notes: "ملاحظات", iqamaNumber: "رقم الإقامة", iqamaIssueDate: "إصدار الإقامة", iqamaExpiryDate: "انتهاء الإقامة", passportNumber: "رقم الجواز", passportCountry: "بلد الجواز", passportIssueDate: "إصدار الجواز", passportExpiryDate: "انتهاء الجواز" };
function RevisionPanel({ isAr }: { isAr: boolean }) {
  const has = useAuthStore(s => s.hasPermission), cache = useQueryClient();
  const [type, setType] = useState(""), [page, setPage] = useState(1), [busy, setBusy] = useState<string | null>(null);
  const subjects = kinds.filter(k => ["employee", "employeeDocument", "companyDocument"].includes(k[0]) && has(`${k[3]}.view`));
  const query = useQuery({ queryKey: ["document-revisions", type, page], queryFn: () => maintenanceApi.revisions(type || undefined, page) });
  async function restore(id: string, version: "before" | "after") { if (!window.confirm(isAr ? "استعادة هذه النسخة مكان بيانات الوثيقة الحالية؟ سيتم حفظ التغيير في السجل." : "Replace the current document with this version? The change will be recorded.")) return; setBusy(id); try { await maintenanceApi.restoreRevision(id, version); await cache.invalidateQueries(); toast.success(isAr ? "تمت استعادة النسخة." : "Version restored."); } catch (error) { toast.error(getErrorMessage(error)); } finally { setBusy(null); } }
  return <Card><CardHeader><CardTitle>{isAr ? "سجل تجديد وتعديل الوثائق" : "Document renewal and revision history"}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{isAr ? "يحفظ التعديلات الجديدة على الإقامة والجواز ومستندات الموظفين والشركة، مع النسخة السابقة والمرفقات واسم من عدّلها. يبدأ التسجيل من تفعيل هذه الميزة." : "New changes to residence permits, passports, employee and company documents retain their previous values, attachments and editor. Recording starts when this feature is enabled."}</p>
    <select className="w-full rounded-xl border bg-background p-3" aria-label={isAr ? "نوع الوثائق" : "Document type"} value={type} onChange={e => { setType(e.target.value); setPage(1); }}><option value="">{isAr ? "كل الوثائق المتاحة" : "All accessible documents"}</option>{subjects.map(([id, ar, en]) => <option key={id} value={id}>{isAr ? ar : en}</option>)}</select>
    {query.isPending ? <Loader2 className="animate-spin" /> : query.isError ? <Button onClick={() => query.refetch()}>{isAr ? "إعادة المحاولة" : "Retry"}</Button> : !query.data?.rows.length ? <p className="py-5 text-center text-sm text-muted-foreground">{isAr ? "لا توجد تعديلات مسجلة بعد." : "No revisions recorded yet."}</p> : query.data.rows.map(row => { const module = kinds.find(k => k[0] === row.subjectType)?.[3]; return <details key={row.id} className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-semibold">{row.subjectName} · {row.documentKind === "IQAMA" ? (isAr ? "إقامة" : "Residence permit") : row.documentKind === "PASSPORT" ? (isAr ? "جواز" : "Passport") : (isAr ? "وثيقة" : "Document")}<small className="block font-normal text-muted-foreground">{row.actorName} · {new Date(row.createdAt).toLocaleString(isAr ? "ar-SA" : "en-GB")}</small></summary><div className="mt-4 grid gap-4 md:grid-cols-2">{(["before", "after"] as const).map(version => <div key={version} className="space-y-2 rounded-xl bg-muted/40 p-3"><b className="text-sm">{version === "before" ? (isAr ? "قبل التعديل" : "Before") : (isAr ? "بعد التعديل" : "After")}</b>{Object.entries(row[version]).filter(([, value]) => value !== null).map(([field, value]) => field.endsWith("FileId") || field === "fileId" ? <Button key={field} size="sm" variant="outline" onClick={() => filesApi.openInNewTab(String(value)).catch(e => toast.error(getErrorMessage(e)))}>{isAr ? "عرض المرفق" : "View attachment"}</Button> : <p key={field} className="break-words text-xs"><span className="text-muted-foreground">{isAr ? labels[field] ?? field : field}: </span>{field.endsWith("Date") ? new Date(String(value)).toLocaleDateString(isAr ? "ar-SA" : "en-GB") : String(value)}</p>)}<Button size="sm" variant="outline" disabled={!!busy || !module || !has(`${module}.edit`)} onClick={() => restore(row.id, version)}>{busy === row.id ? <Loader2 size={14} className="animate-spin" /> : <RotateCcw size={14} />}{isAr ? "استعادة هذه النسخة" : "Restore this version"}</Button></div>)}</div></details>; })}<Pages page={page} total={query.data?.total ?? 0} setPage={setPage} isAr={isAr} />
  </CardContent></Card>;
}
function BackupsPanel({ isAr }: { isAr: boolean }) {
  const admin = useAuthStore(s => s.user?.isSuperAdmin), cache = useQueryClient(), navigate = useNavigate();
  const query = useQuery({ queryKey: ["system-backups"], queryFn: maintenanceApi.backups, enabled: !!admin, refetchInterval: q => q.state.data?.running ? 5000 : false });
  const [password, setPassword] = useState(""), [busy, setBusy] = useState<string | null>(null), [file, setFile] = useState<File | null>(null), [selected, setSelected] = useState<BackupItem | null>(null), [confirmation, setConfirmation] = useState("");
  async function perform(action: string, fn: () => Promise<unknown>, restored = false) { setBusy(action); try { await fn(); setPassword(""); await cache.invalidateQueries(); toast.success(isAr ? (restored ? "تمت الاستعادة. سجّل الدخول مجددًا." : "تمت العملية بنجاح.") : (restored ? "Restored. Sign in again." : "Operation completed.")); if (restored) { keepRefreshToken(undefined); useAuthStore.getState().clearAuth(); cache.clear(); navigate("/login", { replace: true }); } } catch (error) { toast.error(await extractErrorMessage(error)); } finally { setBusy(null); } }
  if (!admin) return <Card><CardContent className="p-6">{isAr ? "إدارة النسخ الاحتياطية متاحة للمسؤول الأعلى فقط." : "Backups are managed by the super administrator only."}</CardContent></Card>;
  const disabled = !password || !!busy || query.data?.running;
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck size={20} />{isAr ? "النسخ الاحتياطي والاستعادة" : "Backup and recovery"}</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm text-muted-foreground">{isAr ? "نسخة مشفرة من بيانات النظام والمرفقات يوميًا الساعة ٣ صباحًا بتوقيت الرياض، مع الاحتفاظ بآخر ٧ نسخ ناجحة. إذا كان الخادم نائمًا يتم التعويض بعد استيقاظه. نزّل نسخة خارجية واحفظ مفتاح تشفير إعدادات النظام بأمان؛ تحتاجه للاستعادة على خادم جديد." : "Encrypted database and attachment backups run daily at 03:00 Riyadh time, retaining the latest 7 successful copies. Sleeping servers catch up after waking. Download an external copy and securely retain the settings encryption key for recovery on a new server."}</p>
    <div className="space-y-1.5"><Label htmlFor="backup-password">{isAr ? "كلمة المرور الحالية لتأكيد العملية" : "Current password to confirm an operation"}</Label><Input id="backup-password" type="password" autoComplete="current-password" maxLength={72} value={password} onChange={e => setPassword(e.target.value)} /></div>
    <div className="flex flex-wrap gap-2"><Button disabled={disabled} onClick={() => perform("create", () => maintenanceApi.createBackup(password))}>{busy === "create" ? <Loader2 size={16} className="animate-spin" /> : <Archive size={16} />}{isAr ? "إنشاء نسخة الآن" : "Back up now"}</Button><Button variant="outline" disabled={disabled || !query.data} onClick={() => perform("schedule", () => maintenanceApi.scheduleBackup(password, !query.data!.enabled))}>{query.data?.enabled ? (isAr ? "إيقاف النسخ اليومي" : "Pause daily backups") : (isAr ? "تفعيل النسخ اليومي" : "Enable daily backups")}</Button></div>
    <p className="text-xs text-muted-foreground">{query.data?.running ? (isAr ? "عملية نسخ أو استعادة جارية…" : "A backup or restore is running…") : query.data?.enabled ? (isAr ? "النسخ اليومي مفعّل" : "Daily backups enabled") : (isAr ? "النسخ اليومي متوقف" : "Daily backups paused")}</p>
    <div className="space-y-2 rounded-xl border p-3"><Label htmlFor="backup-import">{isAr ? "استيراد نسخة مشفرة من جهازك — ZIP حتى 512 ميجابايت" : "Import an encrypted backup ZIP — up to 512 MB"}</Label><Input id="backup-import" type="file" accept=".zip" onChange={e => setFile(e.target.files?.[0] ?? null)} /><Button size="sm" variant="outline" disabled={disabled || !file || file.size > 512 * 1024 * 1024} onClick={() => perform("import", () => maintenanceApi.importBackup(password, file!))}><Upload size={14} />{isAr ? "استيراد وفحص النسخة" : "Import and validate"}</Button><p className="text-xs text-muted-foreground">{isAr ? "الاستيراد يضيف النسخة للقائمة ولا يغيّر بياناتك الحالية." : "Import adds the backup to the list without changing live data."}</p></div>
    {query.isPending ? <Loader2 className="animate-spin" /> : query.isError ? <Button onClick={() => query.refetch()}>{isAr ? "تعذّر التحميل — إعادة المحاولة" : "Could not load — retry"}</Button> : !query.data?.rows.length ? <p>{isAr ? "لا توجد نسخ بعد." : "No backups yet."}</p> : query.data.rows.map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><b className="text-sm">{new Date(row.createdAt).toLocaleString(isAr ? "ar-SA" : "en-GB")}</b><p className="text-xs text-muted-foreground">{row.status === "READY" ? (isAr ? "جاهزة" : "Ready") : row.status === "FAILED" ? (isAr ? "فشلت — راجع التخزين وسجل الخادم" : "Failed — check storage and server logs") : (isAr ? "قيد التنفيذ" : "Running")} · {row.recordCount} {isAr ? "سجل" : "records"} · {row.fileCount} {isAr ? "مرفق" : "files"} · {(row.totalBytes / 1024 / 1024).toFixed(1)} MB</p></div>{row.status === "READY" && <div className="flex gap-2"><Button size="sm" variant="outline" disabled={disabled} onClick={() => perform(row.id, () => maintenanceApi.downloadBackup(password, row.id))}><Download size={14} />{isAr ? "تنزيل" : "Download"}</Button><Button size="sm" variant="outline" disabled={disabled} onClick={() => { setSelected(row); setConfirmation(""); }}><RotateCcw size={14} />{isAr ? "استعادة" : "Restore"}</Button></div>}</div>)}
    <Dialog open={!!selected} onOpenChange={open => { if (!busy && !open) setSelected(null); }}><DialogContent><DialogHeader><DialogTitle>{isAr ? "تأكيد الاستعادة الكاملة" : "Confirm full restore"}</DialogTitle><DialogDescription>{isAr ? "الاستعادة تستبدل البيانات الحالية بالنسخة المحددة وتغلق كل جلسات الدخول. لا يمكن استخدام النظام أثناء الاستعادة." : "Restore replaces current data with the selected snapshot and revokes all sign-in sessions. The system is unavailable while restoration is running."}</DialogDescription></DialogHeader><p className="text-sm">{selected && new Date(selected.createdAt).toLocaleString(isAr ? "ar-SA" : "en-GB")} · {selected?.recordCount} {isAr ? "سجل" : "records"} · {selected?.fileCount} {isAr ? "مرفق" : "files"}</p><Label htmlFor="restore-confirm">{isAr ? "اكتب RESTORE لتأكيد استبدال البيانات" : "Type RESTORE to confirm replacing data"}</Label><Input id="restore-confirm" value={confirmation} onChange={e => setConfirmation(e.target.value)} /><Button variant="destructive" disabled={confirmation !== "RESTORE" || disabled} onClick={() => perform("restore", () => maintenanceApi.restoreBackup(password, selected!.id), true)}>{busy === "restore" ? <Loader2 className="animate-spin" size={16} /> : <RotateCcw size={16} />}{isAr ? "استعادة النسخة المحددة" : "Restore selected snapshot"}</Button></DialogContent></Dialog>
  </CardContent></Card>;
}
export default function MaintenancePage(props: { canEdit?: boolean; isRtl?: boolean } = {}) {
  const { i18n } = useTranslation(), [params, setParams] = useSearchParams();
  const isAr = props.isRtl ?? (i18n.language || "ar").startsWith("ar");
  const tab = ["trash", "revisions", "backups"].includes(params.get("tab") ?? "") ? params.get("tab")! : "trash";
  return <div className="space-y-5"><h2 className="text-xl font-bold">{isAr ? "إدارة وصيانة النظام" : "System maintenance"}</h2><div className="flex flex-wrap gap-2">{[["trash", isAr ? "المحذوفات" : "Recycle bin", Trash2], ["revisions", isAr ? "سجل الوثائق" : "Document history", History], ["backups", isAr ? "النسخ الاحتياطي" : "Backups", Archive]].map(([id, label, Icon]) => { const Component = Icon as typeof Archive; return <Button key={String(id)} variant={tab === id ? "default" : "outline"} onClick={() => setParams({ tab: String(id) }, { replace: true })}><Component size={16} />{String(label)}</Button>; })}</div>{tab === "trash" ? <TrashPanel isAr={isAr} /> : tab === "revisions" ? <RevisionPanel isAr={isAr} /> : <BackupsPanel isAr={isAr} />}</div>;
}
